<<<<<<< HEAD
# Site settings
theme: *folio
title: Nigel Smith
email: nigel@nigelsmith.co.uk
description: Check back for updates often

# > this means to ignore newlines until "baseurl:"
#  A simple, whitespace, helvetica based portfolio theme.
#baseurl:  # the subpath of your site, e.g. /blog/
#url:  # the base hostname & protocol for your site
#twitter_username: twitter_username
#github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

#
#=======
#theme: jekyll-theme-minimal
#title: Nigel Smith
#description: Check back often for updates
>>>>>>> origin/master
